<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2016 Modern Kernel
 */

namespace modernkernel\jeditable;

use yii\base\Widget;
use yii\helpers\Html;
use yii\helpers\Json;

/**
 * Class Editable
 * @package modernkernel\jeditable
 */
class Editable extends Widget
{

    public $tag = 'span';
    public $content = '';
    public $saveUrl = '#';
    public $options = [];
    public $clientOptions = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (empty($this->options['id'])) {
            $this->options['id'] = $this->getId();
        }
        $this->id=$this->options['id'];

    }

    /**
     * @inheritdoc
     */
    public function run()
    {
        $this->registerPlugin();
        $this->registerJS();
        echo Html::beginTag($this->tag, $this->options);
        echo $this->content;
        echo Html::endTag($this->tag);


    }

    /**
     * Registers plugin and the related events
     */
    protected function registerPlugin()
    {
        $view = $this->getView();
        JeditableAsset::register($view);
    }

    /**
     * Register JS
     */
    protected function registerJS()
    {
        $clientOptions = !empty($this->clientOptions) ? Json::encode($this->clientOptions) : '{}';
        $id=$this->getId();
        $js='$("#'.$id.'").editable("'.$this->saveUrl.'", '.$clientOptions.');';

        $this->view->registerJs($js);
    }

} 
